version: "3.8"

services:
  postgres:
    image: postgres:15.1
    restart: always
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6
    env_file:
      - pgadmin.env
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

networks:
  postgres:
    driver: bridge